l2=[['omg ','oh my god '],[' b ',' be '],['4 ',' for'],[' o ',' own '],[' c ',' see '],['isnt ',' is not '],['jb ',' job '],['yo ',' you '],[' t_t ',' crying '],
[' mi ',' my '],["2 ","to "],["24/7 ","Twenty-four hours a day, seven days a week "],["411 ","Information "],["AFAIK ","As far as I know " ],
      ["AFK ","Away from keyboard " ],["Afro ","Natural bush-like hairstyle " ],["AIDS ","Acquired immune deficiency syndrome " ],
      ["AIM ","AOL Instant Messenger " ],["AKA ","Also known as " ],["AM ","Antemeridian " ],["AOL ","America Online " ],["AP","Associated Press" ],
      ["app","Application" ],["APR","Annual percentage rate" ],["ASAP","As soon as possible" ],["ASL","Age, sex, location" ],["ATM","At the moment" ],
      ["b/c","Because" ],["b/w","Between" ],["b4","Before" ],["BAE","Before anyone else" ],["BBIAB","Be back in a bit" ],["BBL","Be back later" ],
      ["BBS","Be back soon" ],["BCC","Blind carbon copy" ],["Beast mode","Dominating gameplay" ],["bf","Boyfriend" ],["BFF","Best friends forever" ],
      ["Bling","Overly flashy jewelry" ],["blog","Web log" ],["BMW","Bayerische Motoren Werke" ],["BRB","Be right back" ],["Bro","Brother" ],["BTW","By the way" ],
      ["Buck","Dollar" ],["Cab","Taxi" ],["CC","Carbon copy" ],["CDC","Centers for Disease Control and Prevention" ],["Chiken","Scared" ],
      ["CPR","Cardiopulmonary resuscitation" ],["Crud","Junk" ],["CTN","Can't talk now" ],["cya","See ya" ],
      ["Cyberbully","A person who bullies someone using technology" ],["CYE","Check your email" ],
      ["Dafuq","What the f***" ],["Dis","Disrespect" ],["Diva","A rude woman" ],["DIY","Do it yourself" ],
      ["dl","Download" ],["DNC","Democratic National Committee" ],["Don't @ me","Don't mention me in your tweets" ],
      ["Dope","Illegal drugs" ],["ER","Emergency room" ],["ETA","Estimated time of arrival" ],["f","Female" ],["Fail","Failure" ],
      ["Fake news","Fake news source that pretends to be real" ],["FAQ","Frequently Asked Questions" ],["fb","Facebook" ],["ft","Featuring" ],
      ["FTW","For the win" ],["FUBAR","Fouled up beyond all recognition" ],["fwd","Forward" ],["FWIW","For what it's worth" ],["FYI","For your information" ],
      ["Gamer","A video game player" ],["Gaslighting","Manipulating information or objects to make a person doubt himself" ],["gf","Girlfriend" ],["GG","Good game" ],
      ["GJ","Good job" ],["GL","Because" ],["GLHF","Good luck have fun" ],["Gold digger","A person who uses another person for money" ],
      ["Googl","To search the Internet" ],["Gotcha","I get you" ],["GPS","Global positioning system" ],["gr8","Great" ],["GTG","Got to go" ],
      ["haha","Laughing" ],["HBO","Home Box Office" ],["High maintenanace","Requiring a lot of attention" ],["HIV","Human immunodeficiency virus" ],
      ["HOAS","Hold on a second" ],["HTH","Hope this helps" ],["HTML","Hyper-Text Markup Language" ],["HTTP","HyperText Transfer Protocol" ],
      ["hw","Homework" ],["IAC","In any case" ],["IC","I see" ],["ICYMI","In case you missed it" ],["IDK","I don't know" ],["IIRC","If I remember correctly" ],
      ["IKR","I know, right?" ],["IM","Instant message" ],["IMO","In my opinion" ],["info","Because" ],["IQ","Intelligence quotient" ],
      ["IRS","Internal Revenue Service" ],["IRT","In regards to" ],["J/K","Just kidding" ],["K","OK" ],["L8","Late" ],["l8r","Later" ],
      ["LAN","Local Area Network" ],["LMAO","Laughing my a** off" ],["LMK","Let me know" ],["LMS","Like my status" ],["LOL","Laughing out loud" ],["m","Male" ],
      ["March Madness","NCAA Men's Division I Basketball Tournament" ],["Mate","Friend" ],["Meme","A piece of media that spreads via the Internet" ],
      ["MLB","Major League Baseball" ],["MMB","Message me back" ],["MMO","Massively multiplayer online" ],["MNF","Monday Night Football" ],
      ["Mooch","To freeload" ],["msg","Message" ],["MVP","Because" ],["MYOB","Mind your own business" ],["N/A","Not Available" ],
      ["NBA","National Basketball Association" ],["NC","No comment" ],["nel","Anyone" ],["NFL","Because" ],["NHL","National Hockey League" ],
      ["NM","Not much" ],["Noob","Because" ],["NP","No problem" ],["NTN","No thanks needed" ],["od","Overdose" ],["OMG","Oh my gosh" ],["OMW","On my way" ],
      ["On fleek","Perfect" ],["OT","Off topic" ],["PC","Because" ],["prev","Pervert" ],["PHAT","Pretty hot and tempting" ],
      ["Photobomb","To pose in the background of a picture being taken" ],["PK","Player kill" ],["pls","Please" ],
      ["PM","Postmeridian" ],["POS"," Parent over shoulder " ],["Pot"," Marijuana " ], ["ppl"," People " ], ["pwn"," To dominate " ], ["qt"," Cutie " ],
      ["RBI"," Runs batted in " ], ["re"," Regarding " ], ["Redflag"," A sign to be cautious " ], ["Redneck"," An uneducated Southerner " ],
      ["RNC"," Republican National Committee " ], ["ROFL"," Rolling on the floor laughing " ], ["ROTFL"," Rolling on the floor laughing " ],
      ["RPG"," Role-playing game " ], ["RSVP"," Répondez s'il vous plaît " ], ["RTFM"," Read the flippin' manual " ], ["sec"," Second " ],
      ["selfi"," A picture of yourself " ], ["Shook"," Completely surprised " ], ["SMH"," Shaking my head " ], ["SMS"," Short Message Service " ],
      ["Soccer mom"," A suburban mom whose world revolves around her kids " ], ["SOS"," Someone over shoulder " ], ["Spam"," Unhelpful and annoying content " ],
      ["Sry"," Sorry " ], ["STD"," Sexually transmitted disease " ], ["sup"," What's up " ], ["Swag"," Skills or style " ], ["Talking trash"," Disrespecting " ],
      ["TBA"," To be announced " ], ["TBC"," To be continued " ], ["TBD"," To be determined " ], ["TC"," Take care " ], ["TFW"," That feeling when " ],
      ["Throwing shade"," Disrespecting " ], ["thx"," Thanks " ], ["TIA"," Thanks in advance " ], ["TLC"," Tender love and care " ], ["TMI"," Too much information " ],
      ["Tree hugger"," A person who cares about the environment " ], ["Troll"," A person who posts offensive comments " ], ["TTFN"," Ta-ta for now " ],
      ["TTYL"," Talk to you later " ], ["Tweet"," Twitter post " ], ["Twitch"," Video game streaming website " ], ["txt"," Text " ], ["TY"," Thank you " ],
      ["u"," You " ], ["U2"," You too " ], ["ugh"," Disgusted " ], ["UR"," Your " ], ["URL"," Uniform Resource Locator " ], ["VAR"," Video assistant referee " ],
      ["VIP"," Very important person " ], ["VM"," Voicemail " ], ["vs"," Versus " ], ["w/"," With " ], ["w/e"," Whatever " ], ["w/o"," Without " ], ["W8"," Wait " ],
      ["wanna"," Want to " ], ["WB"," Write back " ], ["Weed"," Marijuana " ], ["Whipped"," Obedient " ], ["Whoa"," Expression of surprise " ],
      ["Whoops"," Exclamation of a mistake " ], ["Woke"," Awareness of social problems " ], ["WTF"," What the f***" ], ["XDD"," Laughing especially hard " ],
      ["xmas"," Christmas " ], ["XOXO"," Hugs and kisses " ], ["Y"," Why " ], ["YOLO"," You only live once " ], ["yt"," YouTube " ], ["Yuge"," Huge " ],
      ["YW"," You're welcome " ], ["YWA"," You're welcome anyway " ], ["ZZZ"," Sleeping " ]]

